#pragma once

#define ALLEGRO_UNSTABLE
#include <allegro5/allegro.h>
#include <allegro5/allegro_primitives.h>
#include <allegro5/color.h>
#include <allegro5/events.h>
#include <allegro5/keycodes.h>

#include <Agui/Agui.hpp>
#include <Agui/Backends/Allegro5/Allegro5.hpp>
#include <Agui/Widgets/Button/Button.hpp>
#include <Agui/Widgets/CheckBox/CheckBox.hpp>
#include <Agui/Widgets/DropDown/DropDown.hpp>
#include <Agui/Widgets/TextField/TextField.hpp>
#include <Agui/Widgets/Frame/Frame.hpp>
#include <Agui/Widgets/RadioButton/RadioButton.hpp>
#include <Agui/Widgets/RadioButton/RadioButtonGroup.hpp>
#include <Agui/Widgets/Slider/Slider.hpp>
#include <Agui/Widgets/TextBox/ExtendedTextBox.hpp>
#include <Agui/Widgets/Tab/TabbedPane.hpp>
#include <Agui/Widgets/ListBox/ListBox.hpp>
#include <Agui/Widgets/ScrollPane/ScrollPane.hpp>
#include <Agui/FlowLayout.hpp>

#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_generators.hpp>
#include <boost/uuid/uuid_io.hpp>

#include <unordered_map>
#include <unordered_set>
#include <functional>
#include <vector>
#include <string>
#include <cmath>
#include <map>
#include <set>

#include "Color.h"
#include "Colors.h"
#include "ConstantRepository.h"
#include "ConstantSets.h"
#include "Constants.h"
#include "DataTypes.h"
#include "Directories.h"
#include "EventTypes.h"
#include "Events.h"
#include "FileToArray.h"
#include "GameElement.h"
#include "JsonHandler.h"
#include "Logger.h"
#include "NameGenerator.h"
#include "NumTools.h"
#include "Position.h"
#include "PositionStructures.h"
#include "Random_.h"
#include "Size.h"
#include "SystemConstants.h"
#include "WorldRectangle.h"
